### ISSUE TITLE
Jan 31 linked to Feb 1 in book

### ISSUE THREAD

**Issue by jgfender** [IndrajeetPatil/R-Function-A-Day-book#1]
Hi !  The early February dates are off in the book for a week or less, I think by Feb one being linked to Jan 31.  I'm enjoying just now starting to go through your posts. Thank you for the resources!

**Comment by IndrajeetPatil** [comment]
Hi, thanks!

Can you please double-check if this is really the case? 
I went through all tweets for Jan/Feb 2021, and couldn't see any which were incorrectly dated. Please let me know if you still see any inconsistency.

**Comment by jgfender** [comment]
I’m new to GitHub and wondering if I can just reply here.  The date says Feb 1 but post from Jan 31 (then Feb 2 to Feb 1 post, and so on) until it gets to Feb 5 matches to Feb 5.   Unless I’m missing something.  I was making a table of posts I might want to refer back to later (I’m a new R user) and to share with my team who is going to start learning R soon, so noticed the discrepancy from the book date and twitter post date just for 4-5 days (that is as far as I’ve gotten).  Not a big deal at all but I wanted to mention since your book opening page mentioned to report things.  ☺


***@***.******@***.***

**Comment by IndrajeetPatil** [comment]
Closing this for now. Will re-open if someone else also reports something similar.
